services:
  nginx:
    image: 'nginx:1.21.3'
    container_name: nginx
    depends_on:
      - phpfpm
      - elastic
    ports:
      - '80:80'
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./src:/var/www/html:cached
  phpfpm:
    build: './dockerfile/phpfpm'
    container_name: php74
    volumes:
      - ./src:/var/www/html:delegated
      - ./config/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:delegated
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elastic
    restart: always
    environment:
      - discovery.type=single-node
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data:delegated
    ports:
      - 9200:9200
      - 9300:9300
# Network
networks:
    default:
      name: magento 

